services:
  sample-flask:
    build:
      context: ..
      dockerfile: Dockerfile
    ports:
      - "5002:5002"        # тот же порт
    volumes:
      - ..:/code:delegated
    command: ["python", "./app.py"]   # без OTel, чтобы исключить внешний сервис
    environment:
      MONGO_URI: mongodb://root:examplepwd@mongodb:27017
