services:
  sample-flask:
    build:
      context: ..
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ..:/code:delegated
    command: ["python", "./app.py"]          # команда останется, т.к. overrideCommand = false
    environment:
      MONGO_URI: mongodb://root:examplepwd@mongodb:27017
