services:
  sample-flask:
    image: signoz/sample-flask-app:latest   # <-- убрали build
    ports:
      - "5002:5002"
    volumes:
      - ..:/code:delegated                 # live-маунт исходников
    working_dir: /code
    command: ["python", "./app.py"]        # запускаем твой app.py
    environment:
      MONGO_URI: mongodb://root:examplepwd@mongodb:27017
